"../External/Bin/glslc.exe" ../data/shaders/basic.vert -o ../data/shaders/spv/basic.vert.spv
"../External/Bin/glslc.exe" ../data/shaders/basic.frag -o ../data/shaders/spv/basic.frag.spv
"../External/Bin/glslc.exe" ../data/shaders/mesh.vert -o ../data/shaders/spv/mesh.vert.spv
"../External/Bin/glslc.exe" ../data/shaders/mesh.frag -o ../data/shaders/spv/mesh.frag.spv
"../External/Bin/glslc.exe" ../data/shaders/fur.vert -o ../data/shaders/spv/fur.vert.spv
"../External/Bin/glslc.exe" ../data/shaders/fur.frag -o ../data/shaders/spv/fur.frag.spv
"../External/Bin/glslc.exe" ../data/shaders/furShadow.vert -o ../data/shaders/spv/furShadow.vert.spv
"../External/Bin/glslc.exe" ../data/shaders/furShadow.frag -o ../data/shaders/spv/furShadow.frag.spv
"../External/Bin/glslc.exe" ../data/shaders/normaldebug.geom -o ../data/shaders/spv/normaldebug.geom.spv