%VULKAN_SDK%/Bin32/glslc.exe shaders/basic.vert -o shaders/spv/basic.vert.spv
%VULKAN_SDK%/Bin32/glslc.exe shaders/basic.frag -o shaders/spv/basic.frag.spv
%VULKAN_SDK%/Bin32/glslc.exe shaders/mesh.vert -o shaders/spv/mesh.vert.spv
%VULKAN_SDK%/Bin32/glslc.exe shaders/mesh.frag -o shaders/spv/mesh.frag.spv
%VULKAN_SDK%/Bin32/glslc.exe shaders/fur.vert -o shaders/spv/fur.vert.spv
%VULKAN_SDK%/Bin32/glslc.exe shaders/fur.frag -o shaders/spv/fur.frag.spv
%VULKAN_SDK%/Bin32/glslc.exe shaders/furShadow.vert -o shaders/spv/furShadow.vert.spv
%VULKAN_SDK%/Bin32/glslc.exe shaders/furShadow.frag -o shaders/spv/furShadow.frag.spv
%VULKAN_SDK%/Bin32/glslc.exe shaders/normaldebug.geom -o shaders/spv/normaldebug.geom.spv